"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.75;
const nacionalidade = 'brasileira';
const colegas = ['luan', 'maria'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 9, 10, 8.9];
const lista = ['gian', true, 27];
let idadesDeAna = 25;
idadesDeAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
let curso = 'front-end';
